[package]
name = "bunker3"
version.workspace = true
edition = "2021"
license.workspace = true
[lib]
crate-type = ["cdylib", "lib"]
[features]
no-entrypoint = []
[dependencies]
solana-clock = "=2.2.3"
solana-account-info = "=2.3.0"
solana-program-entrypoint = "=2.3.0"
solana-sha256-hasher = { workspace = true }
solana-cpi = "=2.2.1"
solana-program-error = "=2.2.2"
solana-program-pack = "=2.2.1"
solana-pubkey = { version = "=2.4.0", features = ["curve25519"] }
solana-rent = "=2.2.1"
solana-system-interface = { version = "=1.0.0", features = ["bincode"] }
solana-sysvar = "=2.3.0"
spl-token = { version = "=9.0.0", features = ["no-entrypoint"] }
bunker-lmots = { path = "../../crates/bunker-lmots" }
[lints]
workspace = true

